definer/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'definer'

urlpatterns = [
	path('definer_starter/', views.definer_starter, name='definer_starter'),	 #name - чтобы вызывать 
    path('unitaxon/<str:taxon_name>/', views.definer_unitaxon, name='definer_unitaxon'),   #функцию через html
    path('definer_subclass/<int:card_id>/', views.activation, name='activation'),
    path('cards_list/<int:card_id>/', views.activation_in_cards_list, name='activation_in_cards_list'),
    path('activation/<str:taxon_name>/<int:card_id>/', views.activation_in_unitaxon, name='activation_in_unitaxon'),
    path('freezing/<str:taxon_name>/<int:card_id>/', views.card_freezing, name='card_freezing'),
    path('card_freezing_starter/<int:card_id>/', views.card_freezing_starter, name='card_freezing_starter'),
    path('delete_card/<int:card_id>/', views.delete_card, name='delete_card'),
    path('taxons_observation/<str:taxon_name>/<int:card_id>/', views.taxons_observation, name='taxons_observation'),
    path('cards_list/', views.cards_list, name='cards_list'),
    path('cards_list_freezing/<int:card_id>/', views.cards_list_freezing, name='cards_list_freezing'),

]

moss/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'taxons'

urlpatterns = [
	path('species_list/', views.species_list, name='species_list'),
	path('genus_list/', views.genus_list, name='genus_list'),
	path('family_list/', views.family_list, name='family_list'),
	path('order_list/', views.order_list, name='order_list'),
	path('subclass_list/', views.subclass_list, name='subclass_list'),
	path('class_list/', views.class_list, name='class_list'),
	path('division_list/', views.division_list, name='division_list'),
	path('multiple_images/<str:taxon_name>/', views.multiple_images, name='multiple_images'),
	path('main_image/<str:taxon_name>/', views.main_image, name='main_image'),
	path('delete_taxon/<str:taxon_name>/', views.delete_taxon, name='delete_taxon'),
	path('book_add/', views.book_add, name='book_add'),
    path('book/<int:book_id>/', views.book, name='book'),
    path('books/', views.books, name='books'),
    path('all_taxons/', views.all_taxons, name='all_taxons'),
    path('universal_taxon/<str:name>/', views.universal_taxon, name='universal_taxon'),
    path('edition/<str:name>/', views.edition, name='edition'),
    path('new_taxon/', views.new_taxon, name='new_taxon'),
    path('homepage_images/', views.homepage_images, name='homepage_images'),




]

moss_catalog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from moss import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taxons/', include('moss.urls', namespace='taxons')),
    path('definer/', include('definer.urls', namespace='definer')),
    
    path('', views.home, name='home'),
    path('profile/', views.profile_page, name='profile_page'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    path('search/', views.search, name='search'),
    path('base_settings/', views.base_settings, name='base_settings'),
    path('map/', views.to_map, name='to_map'),
    path('add_point/', views.add_point, name='add_point'),
    path('point_page/<int:point_id>/', views.point_page, name='point_page'),
    path('points_list/', views.points_list, name='points_list'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

definer/models.py
from django.db import models
from moss.models import *

class Taxa(models.Model):
	'''Название таксона на русском и английском, для дальнейшего использовани этой информации'''
	name = models.CharField(max_length=150) #на русском
	identifier = models.CharField(max_length=150, null=True) #на английском

	def __str__(self):
		return self.name

class TaxonSearch(models.Model):
	'''Карточки для хранения информации о поиске и отображении её при продвижении по иерархическому дереву таксонов
	во время определения растения'''
	division =  models.CharField(max_length=150, blank=True)
	moss_class = models.CharField(max_length=150, blank=True)
	subclass = models.CharField(max_length=150, blank=True)
	order = models.CharField(max_length=150, blank=True)
	family = models.CharField(max_length=150, blank=True)
	genus = models.CharField(max_length=150, blank=True)
	species = models.CharField(max_length=150, blank=True)

	activation_vars = (
		('Act', 'Act'),
		('Deact', 'Deact'),
		('Frozen', 'Frozen')
		)
	#Определяет текущее состояние карточки. Act - отображается во время поиска и изменяется; Frozen - может продолжать
	#отображаться, но не изменяется; Deact - не  отображается
	activation = models.CharField(max_length=30, choices=activation_vars, default='Act', blank=True)

definer/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from django.contrib.auth.models import User

class SearchCreation(forms.ModelForm):
	class Meta:
		model = TaxonSearch
		fields = '__all__'

definer/views.py
from django.shortcuts import render, redirect
from .models import *
from moss.models import *
from .forms import *
from moss.functions import *
from django.urls import reverse
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.core.files.base import ContentFile

def definer_unitaxon(request, taxon_name):
	'''Функция для отображения всех страниц, кроме стартовой, при перемещении по определителю'''
	obj = TaxonFinder(name=taxon_name)
	taxon = obj.taxon_object()  #нахождение объекта среди всех используемых для создания мхов моделей
	taxon_bounds = obj.taxon_bounds() #связи объекта с имеющими его в качестве ForeignKey объектами
	images = obj.taxon_images() #связанные с ним изображения
	#название модели объекта, для использования его при выборе заполняемого в карточке атрибута
	model = obj.taxon_model()
	
	#Извлечение всех изображений относящихся к данному классу для распределения их среди объектов в html
	tax_images = None
	if taxon_bounds:
		bound_obj = TaxonFinder(name=taxon_bounds[0])
		model = obj.taxon_model()
		tax_images_model = bound_obj.taxon_images_model()
		tax_images = tax_images_model.objects.all()

	try:
		#Извлечение названия объекта поиска для отображения в заголовке						  
		tax_name = str(taxon_bounds[0].tax).lower()
		if taxon_bounds[0].tax == None:
			if model.__name__ == 'Species':
				tax_name = 'вид'
			else:
				tax_name = 'ранг не задан'
	except:
		if model.__name__ == 'Species':
				tax_name = 'вид'
		else:
			tax_name = 'ранг не задан'

	card = None #определяется в следующем блоке кода
	act_button = None
	freez_button_name = None
	button_name = 'Заморозить'
	freez_button_name = 'Разморозить'
	freez_act_button = None

	try:
		freezing_card = list(TaxonSearch.objects.filter(activation='Frozen'))[-1:]
		freez_button_name = 'Разморозить'
		freez_act_button = 'Активировать'
	except:
		freezing_card = None
		button_name = 'Заморозить'
	#добавление названия таксона в карточку, на который до этого нажал пользователь
	try:
		card = TaxonSearch.objects.get(activation='Act')
		act_button = 'Убрать карточку'
		if card:
			print(card.division, end='after if ')
			#дальнейшая многословность вызвана стиранием информации в карточке после манипуляций с ней
			division = card.division
			moss_class = card.moss_class
			subclass = card.subclass
			order = card.order
			family = card.family
			genus = card.genus
			species = card.species

			form = SearchCreation(request.POST, instance=card)
			print(card.division)

			if form.is_valid():
				print(form.is_valid())
				print(obj.taxon_model().__name__)
				print(model.__name__)
				print(model)
				print(division, end='after is_valid ')
				form = form.save(commit=False)

				if model.__name__ == 'Division':
					form.division = str(taxon)
				elif model.__name__ == 'Class':
					form.division = division
					form.moss_class = str(taxon)
				elif model.__name__ == 'Subclass':
					form.division = division
					form.moss_class = moss_class
					form.subclass = str(taxon)
				elif model.__name__ == 'Order':
					form.division = division
					form.moss_class = moss_class
					form.subclass = subclass
					form.order = str(taxon)
				elif model.__name__ == 'Family':
					form.division = division
					form.moss_class = moss_class
					form.subclass = subclass
					form.order = order
					form.family = str(taxon)
				elif model.__name__ == 'Genus':
					form.division = division
					form.moss_class = moss_class
					form.subclass = subclass
					form.order = order
					form.family = family
					form.genus = str(taxon)
				elif model.__name__ == 'Species':
					form.division = division
					form.moss_class = moss_class
					form.subclass = subclass
					form.order = order
					form.family = family
					form.genus = genus
					form.species = str(taxon)

				form.save()

	except:
		card == None
		act_button = 'Активировать'
	context = {'taxon': taxon, 'taxon_bounds': taxon_bounds, 'images': images, 'card': card,
	 'model': model, 'tax_name': tax_name, 'freezing_card': freezing_card, 'button_name': button_name, 
	 'act_button': act_button, 'freez_button_name': freez_button_name,'freez_act_button': freez_act_button,
	 'tax_images': tax_images}
	return render(request, 'definer_unitaxon.html', context)

def taxons_observation(request, taxon_name, card_id):
	'''Функция для перемещения по уже отмеченным в карточке таксонам без опасности утратить информацию
	или изменить ее'''
	obj = TaxonFinder(name=taxon_name)
	taxon = obj.taxon_object()  #нахождение объекта среди всех используемых для создания мхов моделей
	taxon_bounds = obj.taxon_bounds() #связи объекта с имеющими его в качестве ForeignKey объектами
	images = obj.taxon_images() #связанные с ним изображения
	model = obj.taxon_model().__name__ #название модели объекта, для использования его при выборе 
							  #заполняемого в карточке атрибута
	try:
		#Извлечение названия объекта поиска для отображения в заголовке						  
		tax_name = str(taxon_bounds.tax).lower()
		if taxon_bounds.tax == None:
			tax_name = 'ранг не задан'
	except:
		tax_name = 'ранг не задан'

	card = TaxonSearch.objects.get(id=card_id)
	if card.activation == 'Act':
		act_button = 'Убрать карточку'
		button_name = 'Заморозить'
	elif card.activation == 'Deact':
		act_button = 'Активировать карточку'
		button_name = 'Заморозить'
	elif card.activation == 'Frozen':
		act_button = 'Активировать карточку'
		button_name = 'Разморозить'

	context = {'taxon': taxon, 'taxon_bounds': taxon_bounds, 'images': images, 
	'card': card, 'model': model, 'tax_name': tax_name, 'button_name': button_name, 'act_button': act_button}
	return render(request, 'definer_unitaxon.html', context)

def definer_starter(request):
	'''Стартовая страница для движения по определителю, естьотсутсвующаяя на других страницах определителя 
	возможность создать новую карту, перейти к списку всех карт'''
	#все изображения связанные с классом, которые затем будут распределены по связям с объектами
	division_images = DivisionImages.objects.all()
	moss_list = Division.objects.all()
	search_cards = []
	all_cards = TaxonSearch.objects.all()
	card = None

	#нахождение активной карты
	try:
		card = TaxonSearch.objects.get(activation='Act')
		search_cards.append(card)
	except:
		pass
	#получение списка замороженных карт, и добавление в список для вывода одной или двух последних карт
	try:	
		froz_list = TaxonSearch.objects.filter(activation='Frozen')
		froz = list(froz_list)
		print(froz[::-1])
		frozen_cards = [search_cards.append(card) for card in froz[::-1] if len(search_cards) < 2]
	except:
		pass
	print(search_cards)
	#создание новой карты
	form = SearchCreation()
	if request.method == 'POST':
		form = SearchCreation(request.POST)
		if form.is_valid():
			#проверка, чтоб исключить вероятность появления двух активных карт
			act_cards = TaxonSearch.objects.filter(activation='Act')
			if act_cards:
				for card_obj in act_cards:
					if not card_obj == card:
						division = card_obj.division
						moss_class = card_obj.moss_class
						subclass = card_obj.subclass
						order = card_obj.order
						family = card_obj.family
						genus = card_obj.genus
						species = card_obj.species
						form2 = SearchCreation(request.POST, instance=card_obj)
						if form2.is_valid():
							form2 = form2.save(commit=False)
							form2.activation = 'Deact'
							form2.division, form2.moss_class, form2.subclass = division, moss_class, subclass
							form2.order, form2.family, form2.genus, form2.species = order, family, genus, species
							form2.save()
			#сохранение нового объекта в первой форме с состоянием по-умолчанию Act
			form.save()
			#последняя активная карта, до создания новой, становится замороженной
			if card:
				division = card.division
				moss_class = card.moss_class
				subclass = card.subclass
				order = card.order
				family = card.family
				genus = card.genus
				species = card.species
				form2 = SearchCreation(request.POST, instance=card)
				if form2.is_valid():
					form2 = form2.save(commit=False)
					form2.activation = 'Frozen'
					form2.division, form2.moss_class, form2.subclass = division, moss_class, subclass
					form2.order, form2.family, form2.genus, form2.species = order, family, genus, species
					form2.save()

					try:
						act_card = TaxonSearch.objects.get(activation='Act')
						search_cards.append(act_card)
						search_cards.append(card)
					except:
						pass
					
			return redirect('definer:definer_starter')			
	#названия кнопок
	freez_button_name = 'Разморозить'
	button_name = 'Заморозить'

	context = {'moss_list': moss_list, 'division_images': division_images, 
				'form': form, 'search_cards': search_cards, 'button_name': button_name,
				 'freez_button_name': freez_button_name}
	return render(request, 'definer_starter.html', context)

class Activation():
	'''Класс для определения многократно используемых в дальнейшем функций'''
	def __init__(self, card_id, taxon_name=None):
		self.card = TaxonSearch.objects.get(id=card_id)
		self.all_cards = TaxonSearch.objects.all()

		self.taxon = TaxonFinder(name=taxon_name).taxon_object()

		self.division = self.card.division
		self.moss_class = self.card.moss_class
		self.subclass = self.card.subclass
		self.order = self.card.order
		self.family = self.card.family
		self.genus = self.card.genus
		self.species = self.card.species

	def act_func(self, form):
		form = form.save(commit=False)
		form.activation = 'Deact'

		form.division, form.moss_class, form.subclass = self.division, self.moss_class, self.subclass 
		form.order, form.family, form.genus, form.species = self.order, self.family, self.genus, self.species

		form.save()

	def deact_func(self, form, request):
		form = form.save(commit=False)

definer/templates/cards_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<p><a href="{% url 'definer:definer_starter' %}"><button style="margin: 10px" class='back_btn' name='submit'>Назад</button></a></p>

{% for card in cards %}
	<div style='border: 1px solid grey; border-radius: 6px; background: #f8f4ff'>
		Номер: {{card.id}}
		{% if card.division %}
		 | Отдел: <a href="{% url 'definer:taxons_observation' card.division card.id %}"><b>{{card.division}}</b></a>
		{% endif %}
		{% if card.moss_class %}
		 | Класс: <a href="{% url 'definer:taxons_observation' card.moss_class card.id %}"><b>{{card.moss_class}}</b></a>
		 {% endif %}
		{% if card.subclass %}
		 | Подкласс: <a href="{% url 'definer:taxons_observation' card.subclass card.id %}"><b>{{card.subclass}}</b></a>
		{% endif %}
		{% if card.order %}
		 | Порядок: <a href="{% url 'definer:taxons_observation' card.order card.id %}"><b>{{card.order}}</b></a>
		{% endif %}
		{% if card.family %}
		 | Семейство: <a href="{% url 'definer:taxons_observation' card.family card.id %}"><b>{{card.family}}</b></a>
		{% endif %}
		{% if card.genus %}
		 | Род: <a href="{% url 'definer:taxons_observation' card.genus card.id %}"><b>{{card.genus}}</b></a>
		{% endif %}
		{% if card.species %}
		 | Вид: <a href="{% url 'definer:taxons_observation' card.species card.id %}"><b>{{card.species}}</b></a>
		{% endif %}	
		 | Состояние: <b>{{card.activation}}</b>
	<p>

		<form action="{% url 'definer:activation_in_cards_list' card.id %}" method='post' style="display:inline-block;">
			{% csrf_token %}
		<button name='submit' style="background: #00FEAD; color: #1686ab; width: 180px;" class='btn change_act'>Изменить состояние</button>
		</form>

		<form action="{% url 'definer:cards_list_freezing' card.id %}" method='post' style="display:inline-block;">
			{% csrf_token %}
			<button style='background: #00EBFE; width:150px' class='btn third' name='submit'>{% if card.activation == 'Frozen' %}{{freez_button_name}}{% endif %}{% if card.activation == 'Act' %}{{button_name}}{% endif %}{% if card.activation == 'Deact' %}{{button_name}}{% endif %}</button>
		</form>
		<div style='float: right; padding: 1px'>
		<a href="{% url 'definer:delete_card' card.id %}"><button type="button" style="display:inline-block;" class="main_button"  name='submit'>Удалить карточку</button></a>
	</div>
	</p>
	</div>
	<br>

{% endfor %}
{% endblock %}

definer/templates/definer_first_step.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form action="{% url 'definer:definer_first_step' %}" method='post'>
	{% csrf_token %}
	{{form.as_p}}
	<button type='submit'>Определить</button>
</form>

{% endblock %}

definer/templates/definer_starter.html
{% extends 'base.html' %}
{% load static %}
{%load bootstrap4 %}
{% block content %}

<h1 align='center' class='display-4'><strong>Моховидные</strong></h1>
<h2 align='center' class='display-5'>Определение отдела</h2>
<hr>
<br>

<a href="{% url 'definer:cards_list' %}"><button type="button" class="btn btn-success">Посмотреть все карточки</button></a>
<br>
<br>
{% if search_cards %}
	{% for card in search_cards %}
	<div class='card_div'>
		Номер: {{card.id}}
		{% if card.division %}
		 | Отдел: <a href="{% url 'definer:taxons_observation' card.division card.id %}"><b>{{card.division}}</b></a>
		{% endif %}
		{% if card.moss_class %}
		 | Класс: <a href="{% url 'definer:taxons_observation' card.moss_class card.id %}"><b>{{card.moss_class}}</b></a>
		 {% endif %}
		{% if card.subclass %}
		 | Подкласс: <a href="{% url 'definer:taxons_observation' card.subclass card.id %}"><b>{{card.subclass}}</b></a>
		{% endif %}
		{% if card.order %}
		 | Порядок: <a href="{% url 'definer:taxons_observation' card.order card.id %}"><b>{{card.order}}</b></a>
		{% endif %}
		{% if card.family %}
		 | Семейство: <a href="{% url 'definer:taxons_observation' card.family card.id %}"><b>{{card.family}}</b></a>
		{% endif %}
		{% if card.genus %}
		 | Род: <a href="{% url 'definer:taxons_observation' card.genus card.id %}"><b>{{card.genus}}</b></a>
		{% endif %}
		{% if card.species %}
		 | Вид: <a href="{% url 'definer:taxons_observation' card.species card.id %}"><b>{{card.species}}</b></a>
		{% endif %}	
		 | Состояние: <b>{{card.activation}}</b>
	<p>
		<form action="{% url 'definer:activation' card.id %}" method='post' style="display:inline-block;">
			{% csrf_token %}
		<button name='submit' style="background: #00FEAD; color: #1686ab; width: 180px; " class='btn change_act'>Изменить состояние</button>
		</form>


		<form action="{% url 'definer:card_freezing_starter' card.id %}" method='post' style="display:inline-block;">
			{% csrf_token %}
			<button style='background: #00EBFE; width:150px;' class='btn third' name='submit'>{% if card.activation == 'Frozen' %}{{freez_button_name}}{% endif %}{% if card.activation == 'Act' %}{{button_name}}{% endif %}{% if card.activation == 'Deact' %}{{button_name}}{% endif %}</button>
		</form>
		<div style='float: right; padding: 1px'>
		<a href="#zatemnenie"><button type="button" class="main_button" style="display:inline-block;" name='submit'>Удалить карточку</button></a>

		<div id="zatemnenie">

		   <window>
		   		Вы действительно желаете удалить эту карточку?
		   	  <p>
		       <form action="{% url 'definer:delete_card' card.id %}" method='post' style="display:inline-block;">
					{% csrf_token %}
				<button class='form_del_button' name='submit'>Удалить</button>
				</form>
		    	<a href="{% url 'definer:definer_starter' %}"><button type="button" class="cancel_button" style="display:inline-block;" name='submit'>Отмена</button></a>
			  </p>
		   </window>
		</div>
	</div>
	</p>
	</div>
	<br>
	{% endfor %}
{% endif %}
<form action="{% url 'definer:definer_starter' %}" method='post'>
	{% csrf_token %}
	<button name='submit' class='new_card_btn'>Создать поисковую карточку</button>
</form>
<br>
<div class='list-group'>
  {% if moss_list %}
	{% for moss in moss_list %}
		<div style="border: 2px solid #e4dede; border-radius: 6px">
		<p style='text-align: center; height: 180px; padding: 10px; overflow: auto;'>
		{% for photo in division_images %}
			{% if photo.taxon == moss %}
				<a href="{{photo.image.url}}"><img alt='' class="rounded float-center" style="height: 150px; margin:2px;" src='{{photo.image.url}}'></a>

			{% endif %}
		{% endfor %}
		</p>
		
		<a href="{% url 'definer:definer_unitaxon' moss.name %}" class="list-group-item list-group-item-action flex-column align-items-start">
			<div class="d-flex w-100 justify-content-between"></div>
			<div align=center><p><small>{{taxon.tax}}</small></p>
			 <h5 class="mb-3">{{moss.name}}</h5>
			</div>
			 <div class="d-flex w-100 justify-content-between">
			 <p class="mb-3">{{moss.definer_description}}</p>
			</div>
		</a>
		</div>
		<br>
	{% endfor %}
  {% endif %}
</div>

{% endblock %}

definer/templates/delete_card.html
{% extends 'base.html' %}
{% block content %}

<p>Вы действительно хотите удалить эту карточку?</p>
<form method='POST'>
	{% csrf_token %}
	<a href="{% url 'definer:definer_starter' %}"><button type="button" class="btn btn-success">Отмена</button></a>

	<button class='btn btn-danger' name='submit'>Подтвердить удаление</button>
</form>

{% endblock %}

definer/templates/new_definer.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<h3 align='center' class='display-4'>Добавить вид</h3>

<form action="{% url 'definer:add_definer' %}" method='post' enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
		<button name='submit' class='btn btn-primary'>Создать новый определитель</button>
		<button onclick="{% url 'definer:add_definer'%}">edit</button>
	{% endbuttons %}

</form>
<input type="submit" value="Edit Due Date" name="test_butt" />

	<div align='center'><button type="button" class="btn btn-info btn-lg" name='edition_button'>Редактирование</button></a></div>

<form action="{% url 'definer:add_definer' %}" method='get'>
	<input type='submit' name='test'>
</form>

{% endblock %}