moss/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'taxons'

urlpatterns = [
	path('species_list/', views.species_list, name='species_list'),
	path('genus_list/', views.genus_list, name='genus_list'),
	path('family_list/', views.family_list, name='family_list'),
	path('order_list/', views.order_list, name='order_list'),
	path('subclass_list/', views.subclass_list, name='subclass_list'),
	path('class_list/', views.class_list, name='class_list'),
	path('division_list/', views.division_list, name='division_list'),
	path('multiple_images/<str:taxon_name>/', views.multiple_images, name='multiple_images'),
	path('main_image/<str:taxon_name>/', views.main_image, name='main_image'),
	path('delete_taxon/<str:taxon_name>/', views.delete_taxon, name='delete_taxon'),
	path('book_add/', views.book_add, name='book_add'),
    path('book/<int:book_id>/', views.book, name='book'),
    path('books/', views.books, name='books'),
    path('all_taxons/', views.all_taxons, name='all_taxons'),
    path('universal_taxon/<str:name>/', views.universal_taxon, name='universal_taxon'),
    path('edition/<str:name>/', views.edition, name='edition'),
    path('new_taxon/', views.new_taxon, name='new_taxon'),
    path('homepage_images/', views.homepage_images, name='homepage_images'),




]

moss_catalog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from moss import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taxons/', include('moss.urls', namespace='taxons')),
    path('definer/', include('definer.urls', namespace='definer')),
    
    path('', views.home, name='home'),
    path('profile/', views.profile_page, name='profile_page'),
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    path('search/', views.search, name='search'),
    path('base_settings/', views.base_settings, name='base_settings'),
    path('map/', views.to_map, name='to_map'),
    path('add_point/', views.add_point, name='add_point'),
    path('point_page/<int:point_id>/', views.point_page, name='point_page'),
    path('points_list/', views.points_list, name='points_list'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

moss/forms.py
from django import forms
from .models import  *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from django.contrib.auth.models import User

class AddMoreImg(forms.ModelForm):
	class Meta: 
		model =  SpeciesImages
		fields = '__all__'

class CreateUser(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        label = {'username': 'name of user'}
        
class UpdateUser(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']


class SearchForm(ModelForm):
	class Meta:
		model = Species
		fields = ['name']

class UploadFileForm(ModelForm):
	class Meta:
		model = Book
		fields = ['title', 'file']

class AddMossPoint(forms.ModelForm):
	class Meta:
		model = TaxonOnMap
		fields = ['name', 'lat', 'lon', 'image', 'comment']

class HomepageImagesForm(forms.ModelForm):
	class Meta:
		model = HomepageImages
		fields = '__all__'

class AddMultipleImages(forms.Form):
	images = forms.ImageField(label=u'Фотографии', widget=forms.FileInput(attrs={'multiple': 'multiple'}), required=False)




moss/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.forms import ModelForm, Form
from .decoraitors import *
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import Http404, HttpResponseRedirect, HttpResponse
from .filters import OrderFilter, filt_search
from django.db.models import Q
import folium
from folium.plugins import MarkerCluster
from .new_marker import new_marker
from django.core.files.base import ContentFile
from GPSPhoto import gpsphoto
import os
from pathlib import Path
from folium import IFrame
from folium.plugins import FloatImage
from .functions import *
import random
import sys  #потом удалить
import re


def home(request):
	'''Главная страница'''
	species = Species.objects.order_by('name')
	all_obj = Species.objects.all()
	myFilter = OrderFilter(request.GET, queryset=species)
	species = myFilter.qs
	books = Book.objects.order_by('title')
	#количество экземпляров разных моделей для вывода их количества на выпадающей панели навбара
	sp_span = len(Species.objects.all())
	gen_span = len(Genus.objects.all())
	fam_span = len(Family.objects.all())
	order_span = len(Order.objects.all())
	subclass_span = len(Subclass.objects.all())
	class_span = len(Class.objects.all())
	division_span = len(Division.objects.all())
	books_span = len(Book.objects.all())
	points_span = len(TaxonOnMap.objects.all())
	taxons_list = (Division, Class, Subclass, Order, Family, Genus, Species)
	all_tax_span = 0
	for taxon in taxons_list:
		all_tax_span += len(taxon.objects.all())

	definer = request.GET.get('definer_reverse', '')
	if definer:
		return redirect('definer:definer_first_step') 
	#Удаление ненужных символов из сохраненного в тексте списка 5 случайныхобъектов с изображениями
	new_images = HomepageImages.objects.get(id=1).img_field
	bad_chars = [' \'', '\'', '[', ']']
	for i in bad_chars:
		new_images = new_images.replace(i, '')
	#и преобразование текста в список
	list_of_img_objects =  new_images.split(',')
	images_store = [TaxonFinder(name=i).taxon_object() for i in list_of_img_objects]

	context = {'species': species, 'all_obj': all_obj, 'books': books, 
				'myFilter': myFilter, 'sp_span': sp_span, 'gen_span': gen_span, 'books_span': books_span,
			'points_span': points_span, 'subclass_span': subclass_span, 'images_store': images_store, 
			'fam_span': fam_span, 'order_span': order_span, 'class_span': class_span, 'division_span': division_span,'all_tax_span': all_tax_span}
	return render(request, 'home.html', context)

def homepage_images(request):
	'''Отбирает все объекты имеющие атрибут img (используя в цикле for лямбду в сочетании с filter и map,
	затем выбирает из них случайные 10 экземпляров, и выводит на домашней старнице их изображения'''

	models_list = (Division, Class, Subclass, Order, Family, Genus, Species)
	taxons_with_img =  []
	testt = []
	for model in models_list:
		taxons = model.objects.all()
		tax = list(filter(lambda tax: len(tax.img.name) > 0, model.objects.all()))
		test = list(map(lambda i: taxons_with_img.append(i), tax))

	#отбор случайным образом изображений; их уникальность в коллекции гарантируется свойствами множества
	random_set = set()

	counter = 0
	while True:
		random_tax = random.choice(taxons_with_img)
		random_set.add(random_tax)
		counter += 1
		#цикл завершается либо при заполнении множетсва указанным числом экземпляров,
		#либо при достижении лимита попыток, установленного на случай отсутсвия заданного 
		#количества экземпляров с изображениями
		if len(random_set) >= 6 or counter == 50:
			break

	#сохранение множества в виде str в TextField объекта
	form = HomepageImagesForm(instance=HomepageImages.objects.get(id=1))
	if request.method == 'GET':
		form = HomepageImagesForm(request.GET, instance=HomepageImages.objects.get(id=1))
		if form.is_valid():
			form = form.save(commit=False)
			form.img_field = [i.name for i in random_set]
			form.save()

			return HttpResponseRedirect(reverse('home'))

	return render(request, 'home.html')

def base_settings(request):
	'''Поисковая строка в закрепленной верху панели'''
	taxons = (Division, Class, Subclass, Order, Family, Genus, Species)
	search_query = request.GET.get('search', '')
	taxons_list = []
	bad_request = 'К сожалению, по Вашему запросу ничего не найдено. Проверьте запрос.'

	if search_query:
		for taxon in taxons:
			search = taxon.objects.filter(Q(name__icontains=search_query) | Q(description__icontains=search_query))
			if search:
				taxons_list.append(search)
	else:
		for taxon in taxons:
				tax = taxon.objects.all()
				if len(tax) > 0:
					taxons_list.append(tax)
				else:
					pass

	context = {'search_query': search_query, 'taxons_list': taxons_list, 'bad_request': bad_request}
	return render(request, 'taxons_search_list.html', context)


def universal_taxon(request, name):
	'''Универсальная функция для обработки объекта любой модели'''
	obj = TaxonFinder(name=name)
	taxon = obj.taxon_object() #поиск объекта среди всех классов таксонов
	tax = obj.taxon_model() #определение названия класса, содежащего в себе этот объект
	images = obj.taxon_images() #связанные с объектом изображения
	bounds = obj.taxon_bounds() #имеющие объект в атрибуте с ForeignKey

	return render(request, 'universal_taxon.html', {'taxon': taxon, 'images': images})


def all_taxons(request):
	'''Все таксоны'''
	models_list = (Division, Class, Subclass, Order, Family, Genus, Species)
	taxons = []
	for model in models_list:
		taxons2 = list(lambda model: model.objects.all() for model in models_list)
	for model in models_list:
		tax = model.objects.all()
		if len(tax) > 0:
			taxons.append(tax)
		else:
			pass

	return render(request, 'all_taxons.html', {'taxons': taxons})

def edition(request, name):
	'''Универсальная функция для редактирования записей относящихся к любой модели'''
	taxons_list = (Division, Class, Subclass, Order, Family, Genus, Species)
	taxon = None
	tax = None
	for tax in taxons_list:
		try:
			taxon = tax.objects.get(name=str(name))
			tax = tax
		except:
			pass
	if not taxon == None:
		class EditionForm(forms.ModelForm):
			class Meta:
				model = tax
				fields = '__all__'
				exclude = ['creator', 'parent_taxon']

			images = forms.ImageField(label=u'Фотографии', widget=forms.FileInput(attrs={'multiple': 'multiple'}), required=False)


		form = EditionForm(instance=taxon)
		if request.method == 'POST':
			form = EditionForm(request.POST, request.FILES, instance=taxon)
			if form.is_valid():
				form.save()
				return HttpResponseRedirect(reverse('taxons:universal_taxon', args=(taxon.name,)))
	print(taxon.parent_taxon)
	return render(request, 'edition.html', {'form': form, 'taxon': taxon})
	
def species_list(request):
	'''Совокупность функций для вывода все объектов одного из классов - всех видов, всех родов и тд.'''
	taxons_list = Species.objects.order_by('name')

	context = {'taxons_list': taxons_list}
	return render(request, 'taxons_list.html', context)

def genus_list(request):
	taxons_list = Genus.objects.order_by('name')

	return render(request, 'taxons_list.html', {'taxons_list': taxons_list})

def family_list(request):
	taxons_list = Family.objects.order_by('name')

	return render(request, 'taxons_list.html', {'taxons_list': taxons_list})

def order_list(request):
	taxons_list = Order.objects.order_by('name')

	return render(request, 'taxons_list.html', {'taxons_list': taxons_list})

def subclass_list(request):
	taxons_list = Subclass.objects.order_by('name')

	return render(request, 'taxons_list.html', {'taxons_list': taxons_list})

def class_list(request):
	taxons_list = Class.objects.order_by('name')

	return render(request, 'taxons_list.html', {'taxons_list': taxons_list})

def class_list(request):
	taxons_list = Class.objects.order_by('name')

	return render(request, 'taxons_list.html', {'taxons_list': taxons_list})

def division_list(request):
	taxons_list = Division.objects.order_by('name')

	return render(request, 'taxons_list.html', {'taxons_list': taxons_list})

def new_taxon(request):
	'''Создание нового объекта одного из классов в иерархии таксонов. Чтоб не делать для каждого класса отдельную
	функцию, я придумал так: пользователь вводит данные в форму не связанную с моделью, а затем они передаются
	в форму связанную с моделью - название модели берется из атрибута rank первой формы, который выбирает пользователь.
	Функция большая, и можно было бы сделать вместо нее множество однотипных и 
	более простых, но очень хотелось создать именно универсальную функцию :)'''
	taxons = [(i.identifier, i.name) for i in Taxa.objects.all()] #Спиок с названиями всех классов
	class NewTaxon(forms.Form):
		rank = forms.CharField(label='Выберите ранг растения', widget=forms.RadioSelect(choices=taxons))
		name = forms.CharField(label='Название')
		description = forms.CharField(label='Описание таксона', widget=forms.Textarea(), required=False)
		definer_description = forms.CharField(label='Описание таксона для определителя', widget=forms.Textarea(), required=False)
		images = forms.ImageField(label=u'Фотографии', widget=forms.FileInput(attrs={'multiple': 'multiple'}), required=False)

	taxons_list = (Division, Class, Subclass, Order, Family, Genus, Species)
	form = NewTaxon()
	if request.method == 'POST':
		form = NewTaxon(request.POST, request.FILES)
		if form.is_valid():
			rank_type = form.cleaned_data['rank']
			for taxon in taxons_list:
				if rank_type == taxon.__name__:
					#создание второй формы, в которую передадутся данные из первой
					class TaxonCreation(forms.ModelForm):
						class Meta:
							model = taxon
							fields =  '__all__'

moss/templates/all_taxons.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block header %} {% endblock header %}
{% block content %}


<div class="list-group">
	{% if taxons %}
		{% for taxons in taxons %}
			{% for taxon in taxons %}
			  <a href="{% url 'taxons:universal_taxon' taxon.name %}" class="list-group-item list-group-item-action flex-column align-items-start">
			  	<div>
			  	{% if taxon.img %}
			  	<div style='display: inline-block;'>
			  	<img height=100 alt='' src='{{taxon.img.url}}'></div>
			  	{% endif %}
			  	<div style='display: inline-block; padding: 8px'><h3>{{taxon.name}}</h3></div>
			  </div>
			 	<br>
			    <div class="d-flex w-100 justify-content-between">
			    </div>
			    <p class="mb-3">{{taxon.description}}</p>
			    <small>Ранг: <strong>{{taxon.tax}}</strong></small>
			    <small> <b>·</b> Родительский таксон: <strong>{{taxon.parent_taxon}}</strong></small>
			  </a>
			{% endfor %}
		{% endfor %}
	{% endif %}
</div>

{% endblock %}

moss/templates/book.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block header %} {% endblock header %}
{% block content %}

{{book_obj.title}}

{% endblock %}

moss/templates/books.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block header %} {% endblock header %}
{% block content %}

{% if all_books %}
	{% for book_obj in all_books %}
		<p><a href="{% url 'taxons:book' book_obj.id %}">{{book_obj.title}}</a>
		(<small>количество скачиваний - {{book_obj.counter}}</small>)</p>
	{% endfor %}
{% else %}
	<p>Sorry, no books added yet</p>
{% endif %}
{% endblock %}

moss/templates/delete_taxon.html
{% extends 'base.html' %}
{% block content %}

<p>Do you really want to delete {{taxon.name}}?</p>
<form method='POST'>
	{% csrf_token %}
	<a href="{% url 'home' %}">Отмена</a>

	<button class='btn btn-danger' name='submit'>Подтвердить удаление</button>
</form>

{% endblock %}

moss/templates/edition.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<form action="{% url 'taxons:edition' taxon.name %}" method='post' enctype='multipart/form-data'>
	{% csrf_token %}
	{% bootstrap_form form %}
	{{ form.errors }}
	{{ form.non_field_errors }}
	<button class='btn btn-primary' name='submit'>Сохранить изменения</button>
</form>

{% endblock %}

moss/templates/main_image.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<form action="{% url 'taxons:main_image' taxon.name %}" method='post' enctype='multipart/form-data'>
	{% csrf_token %}
	{% bootstrap_form form %}
	<button class='btn btn-primary' name='submit'>Назначить главным фото</button>
</form>
<br>
{% for i in images %}
<img height=150 src="{{i.image.url}}">
{% endfor %}

{% endblock %}

moss/templates/multiple_images_species.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<form action="{% url 'taxons:multiple_images_species' species.id %}" method='post' enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button name='submit'>Добавить изображения</button>
</form>

{% endblock %}

moss/templates/new_taxon.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<h3 align='center' class='display-4'>Добавить таксон</h3>

<form action="{% url 'taxons:new_taxon' %}" method='post' class='form' enctype='multipart/form-data'>
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
	<button name='submit' class='btn btn-primary'>Создать новую запись</button>
	{% endbuttons %}
</form>

{% endblock %}

moss/templates/point_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

{% for point in points %}

	<h3>{{point.name}}</h3>
	{% if point.image %}
		<img class="rounded float" height=150 src='{{point.image.url}}'>
	{% else %}
		<p></p>
	{% endif %}
	<p>{{point.lat}}</p>
	<p>{{point.lon}}</p>
	<p>{{point.comment}}</p>

{% endfor%}

{% endblock %}

moss/templates/point_page.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<h3>{{point.name}}</h3>
{% if point.image %}
	<img class="rounded float" height=350 src='{{point.image.url}}'/>
{% else %}
	<p></p>
{% endif %}
<p>{{point.lat}}</p>
<p>{{point.lon}}</p>
<p>{{point.comment}}</p>


{% endblock %}

moss/templates/registration.html
{% extends 'base.html' %}

{% block content %}

<p>Welcome on Moss Catalogisator. Please, create an account to be able use all functions of the site</p>

<form method='post'>
	{% csrf_token %}
	{{form.username.label}}
    {{form.username}}
    <p>{{form.email.label}}
    {{form.email}}</p>
    <p>{{form.password1.label}}
    {{form.password1}}</p>
    <p>{{form.password2.label}}
    {{form.password2}}</p>
	<input type='submit' name='Create User'>
</form>

{% endblock%}

moss/templates/taxons_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}

<div class="list-group">
	{% if taxons_list %}
		{% for taxon in taxons_list %}
		  <a href="{% url 'taxons:universal_taxon' taxon.name %}" class="list-group-item list-group-item-action flex-column align-items-start">
			<div>
				<div style='display: inline-block;'>
			{% if taxon.img %}
			<img height=100 alt='' src='{{taxon.img.url}}'>
			{% endif %}
		    </div>
				<div style='display: inline-block;'>
					<h3 class="mb-3">{{taxon.name}}</h3>
				</div>
			</div>
		    <div class="d-flex w-100 justify-content-between">
		      <small>{{taxon.date}}</small>
		    </div>
		    <p class="mb-3">{{taxon.description}}</p>
		    <small>Родительский таксон: <strong>{{taxon.parent_taxon}}</strong></small>
		  </a>
		{% endfor %}
	{% else %}
		<b align='center'>{{bad_request}}
			<br><br>
			<p><img height=200 width=200 src="{% static 'sad_smile.png' %}"></p></b>

	{% endif %}
</div>

{% endblock %}